version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleet-management
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fleet_management
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
